unbind -a -T root
# bind -n M-r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded. Check it out!" # Reload config

set -g mouse on
set -s escape-time 0

set -g history-limit 50000

# Visuals
set -g pane-border-lines "double"

# ================ #
# === Indexing === #
# ================ #

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Automatically renumber all windows in a session whenever one is closed, so there are never gaps in the sequence
set -g renumber-windows on

# =================
# === Copy mode ===
# =================
setw -g mode-keys vi

bind -n M-c copy-mode

bind -n S-PageUp copy-mode -u
bind -T copy-mode-vi S-PageUp send -X page-up
bind -T copy-mode-vi S-PageDown send -X page-down

# ======================= #
# === Window selector === #
# ======================= #
bind -n M-Enter new-window

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10

# ===================== #
# === Pane selector === #
# ===================== #
bind -n M-q kill-pane

bind -n C-M-Right split-window -h # New pane to the right
bind -n C-M-Left split-window -hb # New pane to the left
bind -n C-M-Down split-window -v # New pane below
bind -n C-M-Up split-window -vb # New pane above

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
